name: Market Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # 每 5 分钟运行
  workflow_dispatch:  # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: pip install requests tushare
    
    - name: Run monitor script
      run: python monitor.py
